[11/6/2025, 21:08:27] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 21:08:27","stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:144:18)\n    at Object.onceWrapper (node:events:632:28)\n    at Connection.emit (node:events:518:28)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:343:12)","ip_servidor":"localhost"}
[11/6/2025, 21:14:36] INFO: Usuario registrado exitosamente {"usuario_id":"5f8b519f-456c-42ce-bcac-90e25b37bcb2","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1"}
[11/6/2025, 21:14:46] INFO: Inicio de sesión exitoso {"usuario_id":"5f8b519f-456c-42ce-bcac-90e25b37bcb2","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"11/6/2025, 21:14:46"}
[11/6/2025, 21:21:02] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 21:21:02","stack":"SequelizeConnectionError: The server does not support SSL connections\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:76:23)\n    at Object.onceWrapper (node:events:633:26)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)","ip_servidor":"localhost"}
[11/6/2025, 21:21:24] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 21:21:24","stack":"SequelizeConnectionError: la autentificación password falló para el usuario «puntoshein_user»\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","ip_servidor":"localhost"}
[11/6/2025, 21:21:52] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 21:21:52","stack":"SequelizeConnectionError: The server does not support SSL connections\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:76:23)\n    at Object.onceWrapper (node:events:633:26)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)","ip_servidor":"localhost"}
[11/6/2025, 21:25:18] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 21:25:18","stack":"SequelizeConnectionError: The server does not support SSL connections\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:76:23)\n    at Object.onceWrapper (node:events:633:26)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)","ip_servidor":"localhost"}
[11/6/2025, 21:26:03] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 21:26:03","stack":"SequelizeConnectionError: The server does not support SSL connections\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:76:23)\n    at Object.onceWrapper (node:events:633:26)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)","ip_servidor":"localhost"}
[11/6/2025, 21:33:31] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 21:33:31","stack":"SequelizeConnectionError: The server does not support SSL connections\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:76:23)\n    at Object.onceWrapper (node:events:633:26)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)","ip_servidor":"localhost"}
[11/6/2025, 21:36:43] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 21:36:43","stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:144:18)\n    at Object.onceWrapper (node:events:632:28)\n    at Connection.emit (node:events:518:28)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:343:12)","ip_servidor":"localhost"}
[11/6/2025, 21:38:01] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 21:38:01","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d13h7bre5dus73eoma4g-a\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","ip_servidor":"localhost"}
[11/6/2025, 22:45:49] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 22:45:49","stack":"SequelizeConnectionError: la autentificación password falló para el usuario «puntoshein»\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","ip_servidor":"localhost"}
[11/6/2025, 22:48:32] INFO: Sesión cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[11/6/2025, 22:48:32] INFO: Sesión cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[11/6/2025, 22:48:43] INFO: Inicio de sesión exitoso {"usuario_id":"b646c21c-3f81-4168-a29b-019f76d080c8","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"11/6/2025, 22:48:43"}
[11/6/2025, 22:48:53] INFO: Sesión cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[11/6/2025, 22:48:53] INFO: Sesión cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[11/6/2025, 22:49:02] INFO: Inicio de sesión exitoso {"usuario_id":"b646c21c-3f81-4168-a29b-019f76d080c8","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"11/6/2025, 22:49:02"}
[11/6/2025, 22:53:44] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"11/6/2025, 22:53:44","stack":"SequelizeConnectionError: The server does not support SSL connections\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:76:23)\n    at Object.onceWrapper (node:events:633:26)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)","ip_servidor":"localhost"}
[11/6/2025, 22:56:32] INFO: Sesión cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[11/6/2025, 22:56:32] INFO: Sesión cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[11/6/2025, 23:00:32] INFO: Inicio de sesión exitoso {"usuario_id":"b646c21c-3f81-4168-a29b-019f76d080c8","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"11/6/2025, 23:00:32"}
[11/6/2025, 23:02:14] INFO: Inicio de sesión exitoso {"usuario_id":"b646c21c-3f81-4168-a29b-019f76d080c8","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"11/6/2025, 23:02:14"}
[11/6/2025, 23:03:34] INFO: Inicio de sesión exitoso {"usuario_id":"2b76e73a-2073-438b-b39f-ac2b7e152d4d","correo":"luis2004hdez@gmail.com","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"11/6/2025, 23:03:34"}
[11/6/2025, 23:14:11] INFO: Inicio de sesión exitoso {"usuario_id":"b646c21c-3f81-4168-a29b-019f76d080c8","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"11/6/2025, 23:14:11"}
[11/6/2025, 23:14:25] INFO: Sesión cerrada {"ip_cliente":"::1"}
[11/6/2025, 23:14:25] INFO: Sesión cerrada {"ip_cliente":"::1"}
[11/6/2025, 23:14:36] INFO: Inicio de sesión exitoso {"usuario_id":"b646c21c-3f81-4168-a29b-019f76d080c8","correo":"20221061@uthh.edu.mx","ip_cliente":"::1","fecha_hora":"11/6/2025, 23:14:36"}
[11/6/2025, 23:36:20] INFO: Sesión cerrada {"ip_cliente":"::1"}
[11/6/2025, 23:36:20] INFO: Sesión cerrada {"ip_cliente":"::1"}
[11/6/2025, 23:37:07] INFO: Inicio de sesión exitoso {"usuario_id":"b646c21c-3f81-4168-a29b-019f76d080c8","correo":"20221061@uthh.edu.mx","ip_cliente":"::1","fecha_hora":"11/6/2025, 23:37:07"}
[11/6/2025, 23:38:28] INFO: Sesión cerrada {"ip_cliente":"::1"}
[11/6/2025, 23:38:28] INFO: Sesión cerrada {"ip_cliente":"::1"}
[11/6/2025, 23:38:47] INFO: Inicio de sesión exitoso {"usuario_id":"5f8b519f-456c-42ce-bcac-90e25b37bcb2","correo":"20221061@uthh.edu.mx","ip_cliente":"::1","fecha_hora":"11/6/2025, 23:38:47"}
[11/6/2025, 23:50:59] INFO: Sesión cerrada {"ip_cliente":"::1"}
[11/6/2025, 23:50:59] INFO: Sesión cerrada {"ip_cliente":"::1"}
[11/6/2025, 23:51:10] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[11/6/2025, 23:51:14] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[11/6/2025, 23:51:18] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[11/6/2025, 23:51:20] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[11/6/2025, 23:51:23] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[11/6/2025, 23:51:26] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[11/6/2025, 23:51:32] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[11/6/2025, 23:52:57] INFO: Inicio de sesión exitoso {"usuario_id":"5f8b519f-456c-42ce-bcac-90e25b37bcb2","correo":"20221061@uthh.edu.mx","ip_cliente":"::1","fecha_hora":"11/6/2025, 23:52:57"}
[12/6/2025, 0:01:08] INFO: Sesión cerrada {"ip_cliente":"::1"}
[12/6/2025, 0:01:08] INFO: Sesión cerrada {"ip_cliente":"::1"}
[12/6/2025, 0:01:18] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[12/6/2025, 0:01:23] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[12/6/2025, 0:01:24] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[12/6/2025, 0:01:30] ERROR: Credenciales inválidas - Usuario no encontrado {"codigo_error":"400","ip_cliente":"::1","usuario":"luis2004hdez@gmail.com"}
[12/6/2025, 0:36:37] INFO: Inicio de sesión exitoso {"usuario_id":"2b76e73a-2073-438b-b39f-ac2b7e152d4d","correo":"luis2004hdez@gmail.com","ip_cliente":"::1","fecha_hora":"12/6/2025, 0:36:37"}
[12/6/2025, 15:38:57] INFO: Inicio de sesión exitoso {"usuario_id":"b646c21c-3f81-4168-a29b-019f76d080c8","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"12/6/2025, 15:38:57"}
