[7/10/2025, 15:31:39] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"7/10/2025, 15:31:39","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d3anbg75r7bs73d6n0ng-a.oregon-postgres.render.com\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:519:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","ip_servidor":"localhost"}
[7/10/2025, 15:32:05] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"7/10/2025, 15:32:05","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d3anbg75r7bs73d6n0ng-a.oregon-postgres.render.com\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:519:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","ip_servidor":"localhost"}
[7/10/2025, 15:44:56] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"7/10/2025, 15:44:56","stack":"SequelizeConnectionError: read ECONNRESET\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:519:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","ip_servidor":"localhost"}
